Repository inf112-v20/G-Unit, pull requests merged in 2020-03, with the labels that each got.

#45 robot-logic -> multiple-players
  Deliverables/Møtereferater/referat-13-03.md
  Deliverables/Møtereferater/referat-DD-MM.md
  src/main/java/inf112/gunit/player/Player.java
Labels: MVP

#46 Multiple players
  assets/tile_map_3Kx3K_full.tmx
  src/main/java/inf112/gunit/player/Player.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/TestPrograms.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/Menu.java
Labels: MVP

#48 Proper do turn
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/TestPrograms.java
  src/main/java/inf112/gunit/screens/Game.java
Labels: ASAP

#54 Game loop merge request
  assets/tile_map_3Kx3K_full.tmx
  src/main/java/inf112/gunit/GameState.java
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
Labels: ASAP

#57 Mechanic handling
  assets/board_new.tmx
  assets/sprites.tsx
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/Menu.java
Labels: MVP

#59 Flag mechanics implemented
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
Labels: MVP

#66 Implemented test framework
  assets/pixel_sprite_16x16.png
  assets/players_16x16.png
  assets/sprites.tsx
  assets/spritesheet_16x16.tsx
  assets/tile_map_3Kx3K.tmx
  assets/tile_map_3Kx3K_full.tmx
  assets/tiles_80x80.tmx
  pom.xml
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/Menu.java
  src/test/java/inf112/gunit/board/ConveyorTests.java
  src/test/java/inf112/gunit/board/FlagTests.java
  src/test/java/inf112/gunit/board/HoleTests.java
  src/test/java/inf112/gunit/main/GdxTestRunner.java
  src/test/java/inf112/gunit/main/Testing.java
  src/test/java/inf112/gunit/player/ExecuteProgramCardsTests.java
  src/test/java/inf112/gunit/player/MoveTests.java
  src/test/java/inf112/gunit/player/RotationTests.java
Labels: ASAP

#67 Wall mechanics
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
Labels: ASAP, bug

#68 Development -> Master (for release)
  assets/pixel_sprite_16x16.png
  assets/players_16x16.png
  assets/sprites.tsx
  assets/spritesheet_16x16.tsx
  assets/tile_map_3Kx3K.tmx
  assets/tile_map_3Kx3K_full.tmx
  assets/tiles_80x80.tmx
  pom.xml
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/Menu.java
  src/test/java/inf112/gunit/board/ConveyorTests.java
  src/test/java/inf112/gunit/board/FlagTests.java
  src/test/java/inf112/gunit/board/HoleTests.java
  src/test/java/inf112/gunit/main/GdxTestRunner.java
  src/test/java/inf112/gunit/main/Testing.java
  src/test/java/inf112/gunit/player/ExecuteProgramCardsTests.java
  src/test/java/inf112/gunit/player/MoveTests.java
  src/test/java/inf112/gunit/player/RotationTests.java
Labels: ASAP

#69 Update ObligatoriskOppgave3.md
  Deliverables/ObligatoriskOppgave3.md
Labels: ASAP

#70 Update README.md
  README.md
Labels: ASAP, documentation
