Repository inf112-v20/G-Unit, pull requests merged in 2020-05, with the labels that each got.

#89 Fixed the hole bug
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/player/Robot.java
Labels: bug

#91 New game board
  assets/robot_board.tmx
  src/main/java/inf112/gunit/screens/Game.java
Labels: ASAP, MVP

#92 Laser animations
  assets/robot_board.tmx
  src/main/java/inf112/gunit/screens/Game.java
Labels: ASAP, MVP

#93 Removed netcode and updated menu for new features.
  src/main/java/inf112/gunit/network/ClientThread.java
  src/main/java/inf112/gunit/network/Ping.java
  src/main/java/inf112/gunit/network/Pong.java
  src/main/java/inf112/gunit/network/ServerTest.java
  src/main/java/inf112/gunit/network/ServerThread.java
  src/main/java/inf112/gunit/screens/HostScreen.java
  src/main/java/inf112/gunit/screens/JoinScreen.java
  src/main/java/inf112/gunit/screens/Menu.java
Labels: MVP

#97 Robot ai
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/MovementCard.java
  src/main/java/inf112/gunit/player/card/RotationCard.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/player/MoveTests.java
Labels: ASAP, MVP

#96 Robot animations
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/hud/Hud.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/card/CardTests.java
Labels: ASAP, Graphics, MVP

#101 Robot ai
  assets/game_over.wav
  assets/sounds/ouf.wav
  assets/sounds/skrrt.wav
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
Labels: ASAP

#90 AI can die now
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/GameOver.java
Labels: ASAP

#102 Bug fixing
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/Menu.java
Labels: ASAP, MVP

#103 Fixed program card correct priority
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/MovementCard.java
  src/main/java/inf112/gunit/player/card/ProgramCard.java
  src/main/java/inf112/gunit/player/card/RotationCard.java
  src/main/java/inf112/gunit/player/card/TestPrograms.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/card/CardTests.java
  src/test/java/inf112/gunit/player/ExecuteProgramCardsTests.java
Labels: ASAP, MVP

#104 🐛 Robots now receive a damage token when bumping into walls.
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/player/MoveTests.java
Labels: ASAP, MVP, bug

#105 ✨ Implemented easy AI.
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/Menu.java
Labels: ASAP, MVP

#106 📝 Added javadocs.
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/MovementCard.java
  src/main/java/inf112/gunit/screens/Game.java
Labels: documentation

#107 Map fix
  assets/robot_board.tmx
Labels: ASAP, MVP

#109 Written javadoc for remaining methods
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/RRScreen.java
Labels: ASAP

#110 ♻️ Fixed codacy issues.
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/hud/Hud.java
  src/main/java/inf112/gunit/hud/ProgramCardButton.java
  src/main/java/inf112/gunit/main/Main.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/MovementCard.java
  src/main/java/inf112/gunit/player/card/ProgramCard.java
  src/main/java/inf112/gunit/player/card/RotationCard.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/GameOver.java
  src/main/java/inf112/gunit/screens/Menu.java
Labels: Enhance

#111 Some codacy error fixes
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/hud/Hud.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/GameOver.java
  src/main/java/inf112/gunit/screens/Menu.java
  src/test/java/inf112/gunit/hud/HudCardTests.java
  src/test/java/inf112/gunit/hud/PowerDownTests.java
Labels: ASAP, Enhance, MVP

#112 ♻️ Refactoring and fixing Codacy issues.
  src/main/java/inf112/gunit/hud/Hud.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/CardType.java
  src/main/java/inf112/gunit/player/card/ProgramCard.java
  src/test/java/inf112/gunit/board/TurningConveyorTests.java
  src/test/java/inf112/gunit/card/CardTests.java
  src/test/java/inf112/gunit/main/GdxTestRunner.java
  src/test/java/inf112/gunit/player/RobotShootLaserTest.java
Labels: ASAP, Enhance

#113 Refactoring and fixing codacy issues
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/player/Robot.java
  src/test/java/inf112/gunit/card/CardTests.java
  src/test/java/inf112/gunit/main/GdxTestRunner.java
  src/test/java/inf112/gunit/player/MoveTests.java
Labels: ASAP, Enhance
