Repository inf112-v20/G-Unit, pull requests merged in 2020-04, with the labels that each got.

#77 Wall mechanics
  assets/sprites.tsx
  src/main/java/inf112/gunit/board/Direction.java
  src/main/java/inf112/gunit/main/Main.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/player/MoveTests.java
Labels: MVP, bug

#79 Laser mechanics
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/player/RobotShootLaserTest.java
Labels: MVP

#82 Hud
  assets/cursors/arrow.png
  assets/cursors/pointer.png
  assets/hud/card_sprites.png
  assets/hud/damage_token.png
  assets/hud/damage_token_grey.png
  assets/hud/flag_sprites.png
  assets/hud/life_token.png
  assets/hud/life_token_grey.png
  assets/hud/power_down.png
  assets/hud/power_down_grey.png
  assets/hud/program_sheet_bg.png
  assets/hud/submit_green.png
  assets/hud/submit_grey.png
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/hud/Hud.java
  src/main/java/inf112/gunit/hud/ProgramCardButton.java
  src/main/java/inf112/gunit/main/Main.java
  src/main/java/inf112/gunit/player/Robot.java
  src/main/java/inf112/gunit/player/card/CardType.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/board/HoleTests.java
  src/test/java/inf112/gunit/card/CardTests.java
  src/test/java/inf112/gunit/hud/HudCardTests.java
  src/test/java/inf112/gunit/hud/PowerDownTests.java
Labels: MVP

#84 simple_game_over_screen_implemented
  src/main/java/inf112/gunit/screens/Game.java
  src/main/java/inf112/gunit/screens/GameOver.java
Labels: MVP

#85 Implemented lasers
  assets/sprites.tsx
  src/main/java/inf112/gunit/board/Board.java
  src/main/java/inf112/gunit/screens/Game.java
  src/test/java/inf112/gunit/board/LaserTests.java
Labels: ASAP
